language: python

dist: focal

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"

before_install:
  - sudo OS_CACERT=/var/lib/empty docker-compose build --pull
  - mkdir $HOME/.aws
  - touch $HOME/empty.json

install:
  - pip install -r requirements-test.txt

script:
  - make test
  - sudo PASS=testing GOOGLE_APPLICATION_CREDENTIALS=/var/lib/emtpy OS_CACERT=/var/lib/empty docker-compose up -d
  - sh -c 'sleep 10; test "$(curl -4k -u test:testing https://localhost:8443/test)" = "OK"'
