name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-test.txt
      - name: flake8
        run: |
          flake8 --ignore=E501 cloudview/*.py
        continue-on-error: true
      - name: pylint
        run: |
          pylint --disable=line-too-long,R0801 cloudview/*.py

  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: docker/setup-buildx-action@v2
      - name: test docker image
        run: |
          mkdir $HOME/.aws
          OS_CACERT=/abc GOOGLE_APPLICATION_CREDENTIALS=/xyz docker compose build --pull
          OS_CACERT=/abc GOOGLE_APPLICATION_CREDENTIALS=/xyz PASS=testing docker compose up -d
          sleep 10
          test "$(curl -4k -u test:testing https://localhost:8443/test)" = "OK"



