name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-test.txt
      - name: flake8
        run: |
          make flake8
        continue-on-error: true
      - name: black
        run: |
          make black
        continue-on-error: true
      - name: pylint
        run: |
          make pylint
      - name: test
        run: |
          make test
      - name: mypy
        run: |
          make mypy

  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: .

  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: docker/setup-buildx-action@v2
      - name: test docker image
        run: |
          docker compose -f examples/docker-compose.yml --project-directory . build --pull
          PASS=testing docker compose -f examples/docker-compose.yml --project-directory . up -d
          sleep 10
          test "$(curl -4k -u test:testing https://localhost:8443/test)" = "OK"
